obj-$(CONFIG_ARCH_SUNXI) += restart.o
obj-$(CONFIG_ARCH_SUNXI) += sun4i.o
obj-$(CONFIG_ARCH_SUNXI) += sun5i.o
obj-$(CONFIG_ARCH_SUNXI) += sun6i.o
obj-$(CONFIG_ARCH_SUNXI) += sun7i.o
obj-$(CONFIG_SMP) += platsmp.o
